server:
  port: 6001
eureka:
  client:
    service-url:
      defaultZone: http://eureka3001.com:3001/eureka,http://eureka3002.com:3002/eureka,http://eureka3003.com:3003/eureka
spring:
  application:
    name: zuul
zuul:
  ignored-services: "*"
  routes:
    order:
      serviceId: server-order
      path: /order/**
    user:
      serviceId: server-user
      path: /user/**