server:
  port: 3001
eureka:
  instance:
    hostname: eureka3001.com
  server:
    a-s-g-update-interval-ms: 4000
    enable-self-preservation: false
  client:
    fetch-registry: false
    register-with-eureka: false
    service-url:
      defaultZone: http://eureka3002.com:3002/eureka,http://eureka3003.com:3003/eureka